{"name": "test_lambdatest_radio_button_demo_value", "status": "failed", "statusDetails": {"message": "AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 2 failures were found in \"test_lambdatest_radio_button_demo_value\" (test_assertions_soft.AssertionsTest):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"Verify Gender, Title, Age Group\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"C:\\Emi\\uni\\pytest\\First-pytest-project\\DemoPytest\\test_assertions_soft.py\", line 19, in test_lambdatest_radio_button_demo_value\n    self.soft_assert(self.assertIs,\n  File \"C:\\Users\\Emilia Stoyanova\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Emilia Stoyanova\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\unittest\\case.py\", line 1188, in assertIs\n    self.fail(self._formatMessage(msg, standardMsg))\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Emilia Stoyanova\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\unittest\\case.py\", line 732, in fail\n    raise self.failureException(msg)\nAssertionError: 'Male' is not 'Male' : Gender Is Not Correct\n\n-+ [1/2] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"Verify Gender, Title, Age Group\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"C:\\Emi\\uni\\pytest\\First-pytest-project\\DemoPytest\\test_assertions_soft.py\", line 23, in test_lambdatest_radio_button_demo_value\n    self.soft_assert(self.assertIn,\n  File \"C:\\Users\\Emilia Stoyanova\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Emilia Stoyanova\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\unittest\\case.py\", line 1174, in assertIn\n    self.fail(self._formatMessage(msg, standardMsg))\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Emilia Stoyanova\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\unittest\\case.py\", line 732, in fail\n    raise self.failureException(msg)\nAssertionError: '51' not found in '15 - 50' : Age Group Is Not Correct\n\n-+ [2/2] +-", "trace": "self = <test_assertions_soft.AssertionsTest testMethod=test_lambdatest_radio_button_demo_value>\n\n    def test_lambdatest_radio_button_demo_value(self):\n        driver = webdriver.Chrome()\n        driver.maximize_window()\n        driver.get(\"https://www.lambdatest.com/selenium-playground/radiobutton-demo\")\n        driver.find_element(By.XPATH, \"//h4[contains(text(),'Gender')]//following::input[@value='Male']\").click()\n        driver.find_element(By.XPATH, \"//h4[contains(text(),'Age')]//following::input[@value='15 - 50']\").click()\n        driver.find_element(By.XPATH, \"//button[text()='Get values']\").click()\n        gender = driver.find_element(By.CSS_SELECTOR,\".genderbutton\").text\n        age_group = driver.find_element(By.CSS_SELECTOR,\".groupradiobutton\").text\n        print(\"Gender Object: \\t\", id(gender))\n        print(\"Male Object: \\t\", id(\"Male\"))\n        self.soft_assert(self.assertIs,\n        \"Male\", gender, \"Gender Is Not Correct\")\n        self.soft_assert(self.assertTrue,\n        driver.title.__contains__(\"Selenium Grid Online\"))\n        self.soft_assert(self.assertIn,\n        \"51\", age_group, \"Age Group Is Not Correct\")\n>       self.assert_all(\"Verify Gender, Title, Age Group\")\n\nDemoPytest\\test_assertions_soft.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nC:\\Users\\Emilia Stoyanova\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\softest\\case.py:139: in assert_all\n    self.fail(''.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following 2 failures were found in \"test_lambdatest_radio_button_demo_value\" (test_assertions_soft.AssertionsTest):\nE   +----------------------+----------------------+----------------------+\nE    Failure 1 (\"Verify Gender, Title, Age Group\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"C:\\Emi\\uni\\pytest\\First-pytest-project\\DemoPytest\\test_assertions_soft.py\", line 19, in test_lambdatest_radio_button_demo_value\nE       self.soft_assert(self.assertIs,\nE     File \"C:\\Users\\Emilia Stoyanova\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^\nE     File \"C:\\Users\\Emilia Stoyanova\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\unittest\\case.py\", line 1188, in assertIs\nE       self.fail(self._formatMessage(msg, standardMsg))\nE       ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE     File \"C:\\Users\\Emilia Stoyanova\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\unittest\\case.py\", line 732, in fail\nE       raise self.failureException(msg)\nE   AssertionError: 'Male' is not 'Male' : Gender Is Not Correct\nE   \nE   -+ [1/2] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 2 (\"Verify Gender, Title, Age Group\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"C:\\Emi\\uni\\pytest\\First-pytest-project\\DemoPytest\\test_assertions_soft.py\", line 23, in test_lambdatest_radio_button_demo_value\nE       self.soft_assert(self.assertIn,\nE     File \"C:\\Users\\Emilia Stoyanova\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^\nE     File \"C:\\Users\\Emilia Stoyanova\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\unittest\\case.py\", line 1174, in assertIn\nE       self.fail(self._formatMessage(msg, standardMsg))\nE       ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE     File \"C:\\Users\\Emilia Stoyanova\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\unittest\\case.py\", line 732, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '51' not found in '15 - 50' : Age Group Is Not Correct\nE   \nE   -+ [2/2] +-"}, "attachments": [{"name": "stdout", "source": "c640c22e-09b7-4216-bedd-75888a65e313-attachment.txt", "type": "text/plain"}], "start": 1735503066426, "stop": 1735503081765, "uuid": "ada54718-702c-4cbf-a825-2a3093f3ceb9", "historyId": "fb8e3a5b290a357b282c83bfa7826e17", "testCaseId": "fb8e3a5b290a357b282c83bfa7826e17", "fullName": "DemoPytest.test_assertions_soft.AssertionsTest#test_lambdatest_radio_button_demo_value", "labels": [{"name": "parentSuite", "value": "DemoPytest"}, {"name": "suite", "value": "test_assertions_soft"}, {"name": "subSuite", "value": "AssertionsTest"}, {"name": "host", "value": "SOF-LAP-PRL002"}, {"name": "thread", "value": "39924-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "DemoPytest.test_assertions_soft"}]}